# Server Configuration
# http://localhost:8080/swagger-ui/index.html
server.port=8080
server.address=0.0.0.0

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/catalog_app_otchyot
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.properties.sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# mail
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=iskander044ya@yandex.ru
spring.mail.password=yhaxmfvkvmwcrcpo
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# log
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.jdbc.core=TRACE
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.enabled=true